#
# Workaround 1364139
#
--- /usr/lib/python2.7/site-packages/ipaserver/install/server/replicainstall.py	2017-03-23 18:17:12.000000000 +0000
+++ /usr/lib/python2.7/site-packages/ipaserver/install/server/replicainstall.py	2018-09-17 10:16:55.609492132 +0000
@@ -586,7 +586,7 @@
     api.bootstrap(in_server=True, context='installer')
     api.finalize()
 
-    installutils.verify_fqdn(config.master_host_name, options.no_host_dns)
+    installutils.verify_fqdn(config.master_host_name, options.no_host_dns, local_hostname=False)
 
     cafile = config.dir + "/ca.crt"
     if not ipautil.file_exists(cafile):
@@ -1091,7 +1091,7 @@
                            " CA certificate")
 
     installutils.verify_fqdn(config.host_name, options.no_host_dns)
-    installutils.verify_fqdn(config.master_host_name, options.no_host_dns)
+    installutils.verify_fqdn(config.master_host_name, options.no_host_dns, local_hostname=False)
 
     ccache = os.environ['KRB5CCNAME']
     ipautil.kinit_keytab('host/{env.host}@{env.realm}'.format(env=api.env),
#
# Workaround 1377973
#
--- /usr/lib/python2.7/site-packages/ipaserver/install/installutils.py	2017-03-23 18:17:12.000000000 +0000
+++ /usr/lib/python2.7/site-packages/ipaserver/install/installutils.py	2018-09-17 10:17:46.553150313 +0000
@@ -510,7 +510,7 @@
     if len(hostaddr):
         for ha in hostaddr:
             try:
-                ips.append(ipautil.CheckedIPAddress(ha, match_local=True))
+                ips.append(ipautil.CheckedIPAddress(ha, match_local=False))
             except ValueError as e:
                 root_logger.warning("Invalid IP address %s for %s: %s", ha, host_name, unicode(e))
 
